apiVersion: v1
baseDomain: twcc.ai
metadata:
  name: gpu

compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0

controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3

networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16

platform:
  none: {}

fips: false

pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29ncmUwNDAzMWRuemZuZ3V3N3ZtZGJpcWZlaWR4NTJzbHFuOllPOEw5UkwwTEMzN0dVWEs3TjdNMTVRS01SME5PRjgxT05TMTg0QTVSTUxTMUMwVjc2RjVCVU1WSEkyVTFSUUE=","email":"1403035@narlabs.org.tw"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29ncmUwNDAzMWRuemZuZ3V3N3ZtZGJpcWZlaWR4NTJzbHFuOllPOEw5UkwwTEMzN0dVWEs3TjdNMTVRS01SME5PRjgxT05TMTg0QTVSTUxTMUMwVjc2RjVCVU1WSEkyVTFSUUE=","email":"1403035@narlabs.org.tw"},"registry.connect.redhat.com":{"auth":"NTM0NDQ0NzF8dWhjLTFkTnpmbmdVdzd2bURCSXFmRWlkeDUyc0xRbjpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmhZV1ptTnpWaFpqZzVPVE0wTTJKbE9UaGlZell4TnpNME9UUmtPVGswTUNKOS5CY1FucjFUU1RxQ0pRTFE1ZEI5TXFISzJkSl9rd3g4SXduRkpWU0Z6dkEzMXJsRlNwb2R4Y3VuR3VnWmMtNTVKdEFhX3kwWDNZaExGeUhrNE04RnpmOWFpR2NYbnp3OTgtV2hGS29heXVfb0U3c0hrY2tCMjA1Vm5kazNQOWFzWjBsbU1rZGJ6b3Qzc09pZEE5MklvSmdBRk0wNFhvVmktelZTdkgxVkZVTHZNNWF6MTJhSl9vQW01akkxRUtKWldSa09vTnhJYmU1NjhrY2hYZ2VrT3RxdUZEeVktRXBkV0FwR0ZOODBieTlIOTd6WERxQmtIamRLRUMzMW5PQ2ZnNTdYM2VxUjFQUVBkZ2VDalFidnpaR1JOYW1icnR3OFhCb0diczRoczJBX1BRNnhzLVlyZjFNQkZYZ05iUEw2TjRMb2JMZlhKdXduMXpSeURmLVF6Rmdnam9EQU5hcnVHbTY5OER3Wk93VHlkUXVGN2FhaWlYTnBxam1PT2RtMjJkWnhSS2JnZmdZOFFIOHpjTWltYUFCUThMbXRUc1VTMnhmaUdrTE1xX213OGJBZEp5TlRPV2QtMHdmenlrSWpBaTdnTjkwdXRQa0tlS2haZjJGbzZobV9sVHgwanh3Z2pEbEhaVjJ6TXVpTWU3T0lfQjdzRnl3cWpsSnQzRG9IWHJhWko3c3BQWHRyNVVLdWFkVlJtcVo0NWUzdkpTN2tvamtSbXkzQnhDTzA3SDJFUzNJZWxrd2ItSHE4NkEwWndDb1lnQnJ3dGx3dFRIWllGUUE4YnZJbXpGWV9CdU9XTmVrbWJCVWpINUJCeFkzbXQwd3V2OXdmSnRuNzIyYnRIUmY5UUp1MnpuN1BXd3NFTVQwbFFaQmFQZTNka2ZfVjJzUmxycGJwMmw0Yw==","email":"1403035@narlabs.org.tw"},"registry.redhat.io":{"auth":"NTM0NDQ0NzF8dWhjLTFkTnpmbmdVdzd2bURCSXFmRWlkeDUyc0xRbjpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmhZV1ptTnpWaFpqZzVPVE0wTTJKbE9UaGlZell4TnpNME9UUmtPVGswTUNKOS5CY1FucjFUU1RxQ0pRTFE1ZEI5TXFISzJkSl9rd3g4SXduRkpWU0Z6dkEzMXJsRlNwb2R4Y3VuR3VnWmMtNTVKdEFhX3kwWDNZaExGeUhrNE04RnpmOWFpR2NYbnp3OTgtV2hGS29heXVfb0U3c0hrY2tCMjA1Vm5kazNQOWFzWjBsbU1rZGJ6b3Qzc09pZEE5MklvSmdBRk0wNFhvVmktelZTdkgxVkZVTHZNNWF6MTJhSl9vQW01akkxRUtKWldSa09vTnhJYmU1NjhrY2hYZ2VrT3RxdUZEeVktRXBkV0FwR0ZOODBieTlIOTd6WERxQmtIamRLRUMzMW5PQ2ZnNTdYM2VxUjFQUVBkZ2VDalFidnpaR1JOYW1icnR3OFhCb0diczRoczJBX1BRNnhzLVlyZjFNQkZYZ05iUEw2TjRMb2JMZlhKdXduMXpSeURmLVF6Rmdnam9EQU5hcnVHbTY5OER3Wk93VHlkUXVGN2FhaWlYTnBxam1PT2RtMjJkWnhSS2JnZmdZOFFIOHpjTWltYUFCUThMbXRUc1VTMnhmaUdrTE1xX213OGJBZEp5TlRPV2QtMHdmenlrSWpBaTdnTjkwdXRQa0tlS2haZjJGbzZobV9sVHgwanh3Z2pEbEhaVjJ6TXVpTWU3T0lfQjdzRnl3cWpsSnQzRG9IWHJhWko3c3BQWHRyNVVLdWFkVlJtcVo0NWUzdkpTN2tvamtSbXkzQnhDTzA3SDJFUzNJZWxrd2ItSHE4NkEwWndDb1lnQnJ3dGx3dFRIWllGUUE4YnZJbXpGWV9CdU9XTmVrbWJCVWpINUJCeFkzbXQwd3V2OXdmSnRuNzIyYnRIUmY5UUp1MnpuN1BXd3NFTVQwbFFaQmFQZTNka2ZfVjJzUmxycGJwMmw0Yw==","email":"1403035@narlabs.org.tw"}}}
' 
sshKey: 'ssh-rsa AAAAB3N............'
